<?php

$factory->define(App\Patient::class, function (Faker\Generator $faker) {
    return [
        "user_id" => factory('App\User')->create(),
        "township_id" => factory('App\Township')->create(),
        "mpi_code" => $faker->name,
        "date_enrolled" => $faker->date("Y-m-d", $max = 'now'),
        "pmct_code" => $faker->name,
        "name" => $faker->name,
        "dob" => $faker->date("Y-m-d", $max = 'now'),
        "address" => $faker->name,
        "gravida" => $faker->randomNumber(2),
        "parity" => $faker->randomNumber(2),
        "edd" => $faker->date("Y-m-d", $max = 'now'),
        "hiv_status" => collect(["1","0",])->random(),
        "hiv_test_date" => $faker->date("Y-m-d", $max = 'now'),
        "hiv_test_place" => $faker->name,
        "current_art_status" => collect(["1","0",])->random(),
        "current_art_option" => collect(["1","2",])->random(),
        "current_art_start_date" => $faker->date("Y-m-d", $max = 'now'),
        "current_art_unit" => $faker->name,
        "regimen" => $faker->name,
        "int_treatment" => 0,
        "art_code" => $faker->name,
        "vl_test" => 0,
        "vl_test_result" => $faker->randomNumber(2),
        "vl_test_date" => $faker->date("Y-m-d", $max = 'now'),
        "previous_art_history" => 0,
        "previous_art_option" => collect(["1","2","3","4",])->random(),
        "previous_art_history_regimen" => $faker->name,
        "spouse_test_date" => $faker->date("Y-m-d", $max = 'now'),
        "spouse_test_place" => $faker->name,
        "spouse_test_result" => collect(["1","0",])->random(),
        "spouse_art_refer" => collect(["1","0",])->random(),
        "pregnancy_outcome" => collect(["1","2","3","4",])->random(),
        "mod" => collect(["1","2","3",])->random(),
        "dod" => $faker->date("Y-m-d", $max = 'now'),
        "pod" => $faker->name,
        "baby" => collect(["1","2",])->random(),
        "baby_wt" => $faker->randomNumber(2),
        "baby_outcome" => collect(["1","0",])->random(),
        "baby_outcome_dead_date" => $faker->date("Y-m-d", $max = 'now'),
        "pep" => collect(["1","0",])->random(),
        "pep_option" => collect(["1","2",])->random(),
        "pep_not_reason" => $faker->name,
        "cpt" => collect(["1","0",])->random(),
        "cpt_not_reason" => $faker->name,
        "dna_pcr" => collect(["1","0",])->random(),
        "dna_pcr_date" => $faker->date("Y-m-d", $max = 'now'),
        "dna_pcr_result" => collect(["1","0",])->random(),
        "baby_arv" => collect(["1","0",])->random(),
        "baby_arv_no_reason" => $faker->name,
        "baby_txt_start_date" => $faker->date("Y-m-d", $max = 'now'),
        "txt_unit" => $faker->name,
        "txt_regimen" => $faker->name,
        "baby_art_code" => $faker->name,
        "feeding_option" => collect(["1","2","3",])->random(),
        "bf_stop_date" => $faker->date("Y-m-d", $max = 'now'),
        "immunization_bcg_0" => 0,
        "immunization_bcg_2" => 0,
        "immunization_hpt_0" => 0,
        "immunization_penta_2" => 0,
        "immunization_penta_4" => 0,
        "immunization_penta_6" => 0,
        "immunization_pcv" => 0,
        "immunization_pcv_4" => 0,
        "immunization_pcv_6" => 0,
        "immunization_ipv" => 0,
        "immunization_ipv_4" => 0,
        "immunization_ipv6" => 0,
        "baby_outcome1" => collect(["1","0",])->random(),
        "dna_pcr1" => collect(["1","0",])->random(),
        "dna_pcr_date1" => $faker->date("Y-m-d", $max = 'now'),
        "dna_pcr_result1" => collect(["1","0",])->random(),
        "baby_arv1" => collect(["1","0",])->random(),
        "feeding_option1" => collect(["1","2","3",])->random(),
        "baby_outcome2" => collect(["1","0",])->random(),
        "hiv_ab_test" => collect(["1","0",])->random(),
        "hiv_ab_test_date" => $faker->date("Y-m-d", $max = 'now'),
        "hiv_ab_test_not_reason" => $faker->name,
        "hiv_ab_test_result" => collect(["1","0",])->random(),
        "dna_pcr2" => collect(["1","0",])->random(),
        "dna_pcr_date2" => $faker->date("Y-m-d", $max = 'now'),
        "dna_pcr_result2" => collect(["1","0",])->random(),
        "baby_arv2" => collect(["1","0",])->random(),
        "feeding_option2" => collect(["1","2","3",])->random(),
        "immunization_mr" => 0,
        "immunization_mr1" => 0,
        "immunization_je" => 0,
        "baby_outcome3" => collect(["1","0",])->random(),
        "hiv_ab_test1" => collect(["1","0",])->random(),
        "hiv_ab_test_date1" => $faker->date("Y-m-d", $max = 'now'),
        "hiv_ab_test_not_reason1" => $faker->name,
        "hiv_ab_test_result1" => collect(["1","0",])->random(),
        "dna_pcr3" => collect(["1","0",])->random(),
        "dna_pcr_date3" => $faker->date("Y-m-d", $max = 'now'),
        "dna_pcr_result3" => collect(["1","0",])->random(),
        "baby_arv3" => collect(["1","0",])->random(),
        "feeding_option3" => collect(["1","2","3",])->random(),
    ];
});
